### ISSUE TITLE
Algorithms of chevb_approximator.cc 

### ISSUE THREAD

**Issue by Pro7ech** [Alibaba-Gemini-Lab/OpenPEGASUS#1]
Hi,

I ended up on this repository after reading its related paper, which is a very interesting work. As it is very rare to see an actual implementation and those are always welcomed. I haven't tried to run it, but I went trough the code. While doing so, I observed that the vast majority of the code of the file chevb_approximator.cc is taken from [here](https://github.com/ldsec/lattigo/blob/master/ckks/polynomial_evaluation.go). Although this is a rewriting from Go code to C++ code, those algorithms are the implementation of the work `Efficient Bootstrapping for Approximate Homomorphic Encryption with Non-Sparse Keys`,  so the appropriate references would be welcomed.

**Comment by fionser** [comment]
@Pro7ech Thank you for bringing this up. We appreciate the Lattigo team for opening up theirs fantastic implementation.
We have updated the README and cite to Lattigo's repo in the header file of `chevb_approximator.h`.

**Comment by Pro7ech** [comment]
I appreciate, thank you very much :)
