### ISSUE TITLE
Missing second KeySwitch in repacking demo?

### ISSUE THREAD

**Issue by 3553x** [Alibaba-Gemini-Lab/OpenPEGASUS#4]
Hello,
your paper mentions that PEGASUS performs LWE-KeySwitches in two instances in order to reduce the LWE dimension:
* Prior to the LUT evaluation
* After the LUT evaluation

I have taken a look at your example code and I struggle to see where the second KeySwitch occurs. The first KeySwitch seems to occur in `PegasusRunTime::ExtraAllCoefficients`. The only usage of the corresponding switching key I could find is in `PegasusRunTime::MulConstant`.

Did I misread your code or is the second KeySwitch actually missing from the repacking example?

**Comment by fionser** [comment]
Hi
- In `ExtraAllCoefficients` we used a KeySwitch to reduce from a level-2 key (i.e., the largest) to the level-0 (the smallest)
- LUT is working over the level-1.
  - Currently, `MulConstant` is done via one LUT, i.e., takes as input a level-0 LWE and outputs a level-1 LWE.
     To perform further computation (e.g., adding two LWE, or more LUTs) we switch from level-1 LWE to level-0 LWE.
- In other words, a KS (from level-1 to level-0) is added after each LUT.
   see Line 105 and Line 114 in `pegasus_runtime.h`. We use a C-marco to expand our LUTs.

**Comment by 3553x** [comment]
Thanks a lot for clarifying my misunderstanding. My IDE and I missed the second KeySwitch in that macro.
